apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-api-gateway-namespace.yaml
  - 01-api-gateway-configmap.yaml
  - 02-api-gateway-rbac.yaml
  - 03-api-gateway-network-policies.yaml
  - 04-api-gateway.yaml
  - 05-external-secrets.yaml
  - 06-secretStore.yaml
