apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-upload-service-namespace.yaml
  - 01-upload-service-rbac.yaml
  - 02-upload-service-network-policies.yaml
  - 03-upload-service.yaml
